services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: looply
      POSTGRES_PASSWORD: password
      POSTGRES_DB: looply
  
    ports:
      - "5432:5432"

  auth:
    build: ./auth_service
    ports:
      - "4001:4000"
    depends_on:
      - postgres
    env_file:
      - ./auth_service/.env
    networks:
      - default
      
  api_gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - auth
    env_file:
      - ./api_gateway/.env
    networks:
      - default

  notification:
    build: ./notification_service
    ports:
      - "4002:4000"
    depends_on:
      - postgres
    env_file:
      - ./notification_service/.env
    networks:
      - default

  posts:
    build: ./post_service
    ports:
      - "4004:4000"
    depends_on:
      - postgres
      - auth
      - api_gateway
    env_file:
      -  ./post_service/.env
    networks:
      - default


networks:
  default:
    driver: bridge